### ISSUE TITLE
Database name configurable

### ISSUE THREAD

**Issue by mazzy89** [spreaker/prometheus-pgbouncer-exporter#11]
Why is the database name not configurable in the Docker image and set to `pgbouncer`?

**Comment by pracucci** [comment]
Can you elaborate more your question, please?

The database is exported as a label on each metric. The exporter exports
metrics for all databases configured in pgbouncer.

**Comment by mazzy89** [comment]
in the docker image, you can pass different values like username, password, host but in the connection string the database name is hardcoded and it is `pgbouncer`. Any reasons for that?

https://github.com/spreaker/prometheus-pgbouncer-exporter/blob/7a6e2885a4ef48a400243b3038a3763a8de847b0/config.docker.yml#L13

**Comment by pracucci** [comment]
Yes. The pgbouncer metrics are exported by pgbouncer on a "virtual"
database called "pgbouncer".

May you explain your use case, so I will try to better help you, please?

**Comment by mazzy89** [comment]
I've enabled in my app PGBouncer` but I don't have any database called `pgbouncer`. I was just afraid that since I don't have any database `pgbouncer` in there, the connection would fail for that.

**Comment by pracucci** [comment]
Check out the admin console doc:
https://pgbouncer.github.io/usage.html

The exporter just uses that.

**Comment by MaicolBen** [comment]
Yeah, I don't think you can change the pgbouncer's admin database name in the pgbouncer instance.
