### ISSUE TITLE
show databases return pool size?

### ISSUE THREAD

**Issue by fonziesherman** [spreaker/prometheus-pgbouncer-exporter#2]
Hi, this is an excellent exporter.  We are looking at alerting if pool usage is getting close to limits of pool size but it doesnt appear this script returns the pool size metric.  I may submit a PR if I get the time to work on it, unless this was a feature you already considering adding.  Thanks!

**Comment by pracucci** [comment]
I didn't plan to add it, but it makes sense. If you're willing to submit a
PR I will be glad to review and merge it.

**Comment by fonziesherman** [comment]
Thanks, I will try to get something together asap.

**Comment by pracucci** [comment]
The metric `pgbouncer_databases_database_pool_size` is now supported (introduced some time ago by PR #3). I'm going to close this issue.
