### ISSUE TITLE
Wasn't build with Python 3.8.4rc1 and psycopg2==2.7.3.2

### ISSUE THREAD

**Issue by SourFor** [spreaker/prometheus-pgbouncer-exporter#25]
How can I change psycopg2 version to 2.8.5?

**Comment by esanchezm** [comment]
Hi @SourFor. You can fork this repository, change the `requirements.txt` file and the `setup.py` file and create your own package. Or you can do that same changes and send a PR

**Comment by SourFor** [comment]
I can create PR, but I haven't permission.

**Comment by esanchezm** [comment]
You need to fork this repo to your account (you'll find the option at the top right of this page), do the changes in your repository and then [create the Pull request](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork).

**Comment by SourFor** [comment]
Thanks 
PR: /pull/26

**Comment by esanchezm** [comment]
Closed in #26
