### ISSUE TITLE
Cannot get metrics due to Unable to run query

### ISSUE THREAD

**Issue by DanielLund** [spreaker/prometheus-pgbouncer-exporter#46]
When running pgbouncer exporter i get the following errors:

{"asctime": "2022-06-29 16:17:32", "levelname": "ERROR", "message": "Unable run query SHOW STATS on postgresql://postgres:***@localhost:6432/DEV-DB", "exception": "unrecognized configuration parameter \"stats\"\n"}
{"asctime": "2022-06-29 16:17:32", "levelname": "ERROR", "message": "Unable run query SHOW POOLS on postgresql://postgres:***@localhost:6432/DEV-DB", "exception": "unrecognized configuration parameter \"pools\"\n"}
{"asctime": "2022-06-29 16:17:32", "levelname": "ERROR", "message": "Unable run query SHOW DATABASES on postgresql://postgres:***@localhost:6432/DEV-DB", "exception": "unrecognized configuration parameter \"databases\"\n"}
{"asctime": "2022-06-29 16:17:32", "levelname": "ERROR", "message": "Unable run query SHOW CONFIG on postgresql://postgres:***@localhost:6432/DEV-DB", "exception": "unrecognized configuration parameter \"config\"\n"}
{"asctime": "2022-06-29 16:17:32", "levelname": "INFO", "message": "Exporter listening on 0.0.0.0:9100"}
{"asctime": "2022-06-29 16:17:33", "levelname": "ERROR", "message": "Unable run query SHOW STATS on postgresql://postgres:***@localhost:6432/DEV-DB", "exception": "unrecognized configuration parameter \"stats\"\n"}
{"asctime": "2022-06-29 16:17:33", "levelname": "ERROR", "message": "Unable run query SHOW POOLS on postgresql://postgres:***@localhost:6432/DEV-DB", "exception": "unrecognized configuration parameter \"pools\"\n"}
{"asctime": "2022-06-29 16:17:33", "levelname": "ERROR", "message": "Unable run query SHOW DATABASES on postgresql://postgres:***@localhost:6432/DEV-DB", "exception": "unrecognized configuration parameter \"databases\"\n"}
{"asctime": "2022-06-29 16:17:33", "levelname": "ERROR", "message": "Unable run query SHOW CONFIG on postgresql://postgres:***@localhost:6432/DEV-DB", "exception": "unrecognized configuration parameter \"config\"\n"}

I have added the user for the db i am using pgbouncer for to both admin_users and stats_users

not sure what else to do.

**Comment by DanielLund** [comment]
When changing the database to pgbouncer i get the following error {"asctime": "2022-06-29 17:23:33", "levelname": "ERROR", "message": "Unable fetch metrics from postgresql://postgres:***@127.0.0.1:6432/pgbouncer", "exception": "connection to server at \"127.0.0.1\", port 6432 failed: FATAL:  not allowed\n"}

**Comment by anwareset** [comment]
Hi @DanielLund 

> All sorted, had to change the pg_hba.conf file

Can you share your `pg_hba.conf` file? Im facing similar issue.
