### ISSUE TITLE
Any chance for a dockerhub image?

### ISSUE THREAD

**Issue by jmccarty3** [spreaker/prometheus-pgbouncer-exporter#9]
Since there is now a Dockerfile in the repository, is there any chance a dockerhub build could be attached to the repo to build the container? I would like to use this project in a kubernetes environment and having the container available would make that much easier.

**Comment by pracucci** [comment]
_Looks a good idea. I should have some spare time to do it today. I will keep you posted on this._

**Comment by pracucci** [comment]
The exporter has been published to Docker hub:
https://hub.docker.com/r/spreaker/prometheus-pgbouncer-exporter/
